In [1]:
from hmm import *
import numpy as np

In [2]:
#np.array([[0.2, 0.8], [0.2, 0.8]])
#np.array([[0.8, 0.2], [0.8, 0.2]])
hmm0 = hmm(A = np.array([[0.5, 0.5], [0.5, 0.5]]), B = np.array([[0.95, 0.05], [0.05, 0.95]]))
print('true')
print(np.round(hmm0.A, 2))
print(np.round(hmm0.B, 2))

model = learn_hmm(hmm = hmm0, n_state = 2, eta = 0.0005, a0 = None, b0 = None)
print()
print('start')
print(np.round(model.a, 2))
print(np.round(model.b, 2))

model.learn(10000)
print()
print('estimated')
print(np.round(model.a, 2))
print(np.round(model.b, 2))

true
[[0.5 0.5]
 [0.5 0.5]]
[[0.95 0.05]
 [0.05 0.95]]

start
[[0.48 0.52]
 [0.5  0.5 ]]
[[0.45 0.55]
 [0.54 0.46]]

estimated
[[0. 1.]
 [0. 1.]]
[[0.43 0.57]
 [0.5  0.5 ]]
